### ISSUE TITLE
Add remaining Hive-Engine operations

### ISSUE THREAD

**Issue by stoodkev** [hive-keychain/hive-keychain-mobile#9]
**Is your feature request related to a problem? Please describe.**
Currently, users can only check history and make transfers of their HE tokens.
**Describe the solution you'd like**
Implement staking and other HE operations
**Additional context**
Related documentation from HE team is welcome

**Comment by 4Ykw** [comment]
Yeah, OK, I understand. For recurring automatic stuff of course. I mean, otherwise, people need to understand that Automated services have a cost to implement/support/maintain. A small fee initially will be irrelevant to many users that wish to use this and will take off very quickly I would say.

For manual stuff no. It should be free and if you still need support, I would recommend reflecting that on the proposal.

HE features should be free up to a certain point. Basically, anything that is already provided by the basic stuff available via the API and some contracts (maybe later), should be kept free in my view. That's where you are getting the "adoption". Then anything that uses automation... with one exception (you already made the recurring transfers available for example, I would also add recurring staking operations). Those two, if possible to still provide them as free and reflect that on the proposal because they benefit HIVE.

How it should be implemented is up to you guys, but as you suggested, either using percentages or with a sort of subscription that gives access to automation. I prefer the static subscription, but sometimes those are harder to scale for the business.

**Comment by stoodkev** [comment]
Thanks for your input!
I was referring to automated tasks only, all basic Keychain features, including HE, will always be free, don't worry about it.
